AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  planwise-api
  SAM Template for Event Management API

# ============================================================================
# PARAMETERS
# ============================================================================
Parameters:
  DynamoDBEndpoint:
    Type: String
    Default: ""
    Description: "DynamoDB endpoint URL for local development (leave empty for AWS)"

# ============================================================================
# GLOBALS
# ============================================================================
Globals:
  Function:
    Runtime: python3.13
    Architectures:
      - x86_64
    Timeout: 30
    Environment:
      Variables:
        AWS_ENDPOINT_URL: !Ref DynamoDBEndpoint
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

# ============================================================================
# RESOURCES
# ============================================================================
Resources:
  # --------------------------------------------------------------------------
  # Lambda Layers
  # --------------------------------------------------------------------------
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: planwise-api-dependencies
      Description: Shared dependencies including Pydantic and models
      ContentUri: layers/dependencies
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile

  # --------------------------------------------------------------------------
  # DynamoDB Tables
  # --------------------------------------------------------------------------
  EventTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: event-table
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: board_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: board_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE



  # --------------------------------------------------------------------------
  # Event Functions
  # --------------------------------------------------------------------------
  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: create_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /event
            Method: post

  GetEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: get_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /event/{id}
            Method: get

  UpdateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: update_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            Path: /event/{id}
            Method: put

  DeleteEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: delete_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            Path: /event/{id}
            Method: delete

# ============================================================================
# OUTPUTS
# ============================================================================
Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"

  EventTableName:
    Description: "DynamoDB table name for event"
    Value: !Ref EventTable

  CreateEventFunctionArn:
    Description: "Create Event Lambda Function ARN"
    Value: !GetAtt CreateEventFunction.Arn