AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  planwise-api
  SAM Template for Event Management API

# ============================================================================
# PARAMETERS
# ============================================================================
Parameters:
  DynamoDBEndpoint:
    Type: String
    Default: ""
    Description: "DynamoDB endpoint URL for local development (leave empty for AWS)"

# ============================================================================
# GLOBALS
# ============================================================================
Globals:
  Function:
    Runtime: python3.13
    Architectures:
      - x86_64
    Timeout: 30
    Environment:
      Variables:
        AWS_ENDPOINT_URL: !Ref DynamoDBEndpoint
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

# ============================================================================
# RESOURCES
# ============================================================================
Resources:
  # --------------------------------------------------------------------------
  # Lambda Layers
  # --------------------------------------------------------------------------
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: planwise-api-dependencies
      Description: Shared dependencies including Pydantic and models
      ContentUri: layers/dependencies
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile

  # --------------------------------------------------------------------------
  # DynamoDB Tables
  # --------------------------------------------------------------------------
  EventTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: event-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: calendar_id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: calendar_id-index
          KeySchema:
            - AttributeName: calendar_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  CalendarsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: calendars-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # --------------------------------------------------------------------------
  # Calendar Functions
  # --------------------------------------------------------------------------
  CreateCalendarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/calendar/
      Handler: create_calendar.lambda_handler
      Environment:
        Variables:
          CALENDARS_TABLE: !Ref CalendarsTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CalendarsTable
      Event:
        CreateCalendar:
          Type: Api
          Properties:
            Path: /calendars
            Method: post

  GetCalendarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/calendar/
      Handler: get_calendar.lambda_handler
      Environment:
        Variables:
          CALENDARS_TABLE: !Ref CalendarsTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CalendarsTable
      Event:
        GetCalendar:
          Type: Api
          Properties:
            Path: /calendars/{id}
            Method: get

  UpdateCalendarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/calendar/
      Handler: update_calendar.lambda_handler
      Environment:
        Variables:
          CALENDARS_TABLE: !Ref CalendarsTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CalendarsTable
      Event:
        UpdateCalendar:
          Type: Api
          Properties:
            Path: /calendars/{id}
            Method: put

  DeleteCalendarFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/calendar/
      Handler: delete_calendar.lambda_handler
      Environment:
        Variables:
          CALENDARS_TABLE: !Ref CalendarsTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CalendarsTable
      Event:
        DeleteCalendar:
          Type: Api
          Properties:
            Path: /calendars/{id}
            Method: delete

  GetDateRangeEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/calendar
      Handler: get_calendar_event_by_date_range.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventTable
      Event:
        GetDateRangeEvent:
          Type: Api
          Properties:
            Path: /calendars/{calendar_id}/event
            Method: get

  # --------------------------------------------------------------------------
  # Event Functions
  # --------------------------------------------------------------------------
  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: create_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
      Event:
        CreateEvent:
          Type: Api
          Properties:
            Path: /event
            Method: post

  GetEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: get_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventTable
      Event:
        GetEvent:
          Type: Api
          Properties:
            Path: /event/{id}
            Method: get

  UpdateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: update_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
      Event:
        UpdateEvent:
          Type: Api
          Properties:
            Path: /event/{id}
            Method: put

  DeleteEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: delete_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
      Event:
        DeleteEvent:
          Type: Api
          Properties:
            Path: /event/{id}
            Method: delete

# ============================================================================
# OUTPUTS
# ============================================================================
Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"

  EventTableName:
    Description: "DynamoDB table name for event"
    Value: !Ref EventTable

  CalendarsTableName:
    Description: "DynamoDB table name for calendars"
    Value: !Ref CalendarsTable

  CreateEventFunctionArn:
    Description: "Create Event Lambda Function ARN"
    Value: !GetAtt CreateEventFunction.Arn