AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  planwise-api
  SAM Template for Event Management API

# ============================================================================
# PARAMETERS
# ============================================================================
Parameters:
  DynamoDBEndpoint:
    Type: String
    Default: ""
    Description: "DynamoDB endpoint URL for local development (leave empty for AWS)"

# ============================================================================
# GLOBALS
# ============================================================================
Globals:
  Function:
    Runtime: python3.13
    Architectures:
      - arm64
    Timeout: 30
    Environment:
      Variables:
        AWS_ENDPOINT_URL: !Ref DynamoDBEndpoint
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

# ============================================================================
# RESOURCES
# ============================================================================
Resources:
  # --------------------------------------------------------------------------
  # Lambda Layers
  # --------------------------------------------------------------------------
  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: planwise-api-dependencies
      Description: Shared dependencies including Pydantic and models
      ContentUri: layers/dependencies
      CompatibleRuntimes:
        - python3.13
      CompatibleArchitectures: 
      - arm64      
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: arm64

  # --------------------------------------------------------------------------
  # DynamoDB Tables
  # --------------------------------------------------------------------------
  EventTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: event-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  FolderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: folder-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  BoardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: board-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  TagTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: tag-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: task-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  # --------------------------------------------------------------------------
  # Event Functions
  # --------------------------------------------------------------------------
  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: create_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /board/event
            Method: post

  GetEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: get_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /board/{board_id}/event/{id}
            Method: get

  GetEventsByBoardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: get_events_by_board.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /board/{board_id}/event/
            Method: get

  UpdateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: update_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            Path: /board/{board_id}/event/{id}
            Method: put

  DeleteEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/event/
      Handler: delete_event.lambda_handler
      Environment:
        Variables:
          EVENT_TABLE: !Ref EventTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventTable
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            Path: /board/{board_id}/event/{id}
            Method: delete
  # --------------------------------------------------------------------------
  # Folder Functions 
  # --------------------------------------------------------------------------

  CreateFolderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/folder/
      Handler: create_folder.lambda_handler
      Environment:
        Variables:
          FOLDER_TABLE: !Ref FolderTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FolderTable
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /user/folder
            Method: post

  GetFolderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/folder/
      Handler: get_folder.lambda_handler
      Environment:
        Variables:
          FOLDER_TABLE: !Ref FolderTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FolderTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /user/{user_id}/folder/{id}
            Method: get

  UpdateFolderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/folder/
      Handler: update_folder.lambda_handler
      Environment:
        Variables:
          FOLDER_TABLE: !Ref FolderTable 
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FolderTable 
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            Path: /user/{user_id}/folder/{id}
            Method: put

  DeleteFolderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/folder/
      Handler: delete_folder.lambda_handler
      Environment:
        Variables:
          FOLDER_TABLE: !Ref FolderTable 
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FolderTable
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            Path: /user/{user_id}/folder/{id}
            Method: delete

  GetFoldersByDepthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/folder/
      Handler: get_folders_by_depth.lambda_handler
      Environment:
        Variables:
          FOLDER_TABLE: !Ref FolderTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FolderTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /user/{user_id}/folder/{depth}/{path+}
            Method: get
  # --------------------------------------------------------------------------
  # Board Functions 
  # --------------------------------------------------------------------------

  CreateBoardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/board/
      Handler: create_board.lambda_handler
      Environment:
        Variables:
          BOARD_TABLE: !Ref BoardTable 
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BoardTable
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /user/board
            Method: post

  GetBoardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/board/
      Handler: get_board.lambda_handler
      Environment:
        Variables:
          BOARD_TABLE: !Ref BoardTable 
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BoardTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /user/{user_id}/board/{id}
            Method: get

  GetBoardsByDepthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/board/
      Handler: get_boards_by_depth.lambda_handler
      Environment:
        Variables:
          BOARD_TABLE: !Ref BoardTable 
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BoardTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /user/{user_id}/board/{depth}/{path+}
            Method: get
  UpdateBoardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/board/
      Handler: update_board.lambda_handler
      Environment:
        Variables:
          BOARD_TABLE: !Ref BoardTable 
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BoardTable 
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            Path: /user/{user_id}/board/{id}
            Method: put

  DeleteBoardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/board/
      Handler: delete_board.lambda_handler
      Environment:
        Variables:
          BOARD_TABLE: !Ref BoardTable 
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BoardTable
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            Path: /user/{user_id}/board/{id}
            Method: delete

  GetBoardsByUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/board/
      Handler: get_boards_by_user.lambda_handler
      Environment:
        Variables:
          BOARD_TABLE: !Ref BoardTable 
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BoardTable
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            Path: /user/{user_id}/board/
            Method: get


  # --------------------------------------------------------------------------
  # Tag Functions 
  # --------------------------------------------------------------------------

  CreateTagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/tag/
      Handler: create_tag.lambda_handler
      Environment:
        Variables:
          TAG_TABLE: !Ref TagTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TagTable
      Events:
        CreateTag:
          Type: Api
          Properties:
            Path: /user/tag
            Method: post

  GetTagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/tag/
      Handler: get_tag.lambda_handler
      Environment:
        Variables:
          TAG_TABLE: !Ref TagTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TagTable
      Events:
        GetTag:
          Type: Api
          Properties:
            Path: /user/{user_id}/tag/{id}
            Method: get

  UpdateTagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/tag/
      Handler: update_tag.lambda_handler
      Environment:
        Variables:
          TAG_TABLE: !Ref TagTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TagTable
      Events:
        UpdateTag:
          Type: Api
          Properties:
            Path: /user/{user_id}/tag/{id}
            Method: put

  DeleteTagFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/tag/
      Handler: delete_tag.lambda_handler
      Environment:
        Variables:
          TAG_TABLE: !Ref TagTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TagTable
      Events:
        DeleteTag:
          Type: Api
          Properties:
            Path: /user/{user_id}/tag/{id}
            Method: delete

  # --------------------------------------------------------------------------
  # Task Functions 
  # --------------------------------------------------------------------------

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/task/
      Handler: create_task.lambda_handler
      Environment:
        Variables:
          TASK_TABLE: !Ref TaskTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskTable
      Events:
        CreateTask:
          Type: Api
          Properties:
            Path: /board/task
            Method: post

  GetTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/task/
      Handler: get_task.lambda_handler
      Environment:
        Variables:
          TASK_TABLE: !Ref TaskTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TaskTable
      Events:
        GetTask:
          Type: Api
          Properties:
            Path: /board/{board_id}/task/{id}
            Method: get

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/task/
      Handler: update_task.lambda_handler
      Environment:
        Variables:
          TASK_TABLE: !Ref TaskTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskTable
      Events:
        UpdateTask:
          Type: Api
          Properties:
            Path: /board/{board_id}/task/{id}
            Method: put

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/task/
      Handler: delete_task.lambda_handler
      Environment:
        Variables:
          TASK_TABLE: !Ref TaskTable
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskTable
      Events:
        DeleteTask:
          Type: Api
          Properties:
            Path: /board/{board_id}/task/{id}
            Method: delete
# ============================================================================
# OUTPUTS
# ============================================================================
Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"

  EventTableName:
    Description: "DynamoDB table name for event"
    Value: !Ref EventTable

  CreateEventFunctionArn:
    Description: "Create Event Lambda Function ARN"
    Value: !GetAtt CreateEventFunction.Arn
